config/routes.rb
Rails.application.routes.draw do
  resources :letters
  post "/letters/:id/duplicate", to: "letters#duplicate", as: 'duplicate_letter'
  post "/letters/:id/format", to: "letters#format", as: 'format_letter'
  post "/letters/:id/select-legislators", to: "letters#select_legislators", as: 'select_legislator_letter'
  resources :categories
  root 'welcome#index'
  get "/congress_critters", to:"congress_critters#index", as: 'congress_critters'
  get "/districts", to:"districts#index", as: 'districts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/letter.rb
require 'despamilator'
require 'kramdown' 
class Letter < ApplicationRecord
  has_and_belongs_to_many :categories
  default_scope { where(public: true) }
  before_save :update_spam_score
  before_create :update_spam_score
  before_update :update_spam_score

  include PgSearch
  # The index must include the weightings and fields
  # see db/migrate/20170204152255_create_full_text_index.rb
  # for an example of how it was initally done.
  #
  # To check if the index is being used `set enable_seqscan=false;`
  # e.g.
  #
  # lettersource_development=> set enable_seqscan=false;
  # lettersource_development=> explain SELECT "letters".* FROM "letters" INNER
  # JOIN (SELECT "letters"."id" AS pg_search_id,
  # (ts_rank((setweight(to_tsvector('english',
  # coalesce("letters"."title"::text, '')), 'A') ||
  # setweight(to_tsvector('english', coalesce("letters"."body"::text, '')),
  # 'B')), (to_tsquery('english', ''' ' || 'tab' || ' ''')), 0)) AS rank FROM
  # "letters" WHERE (((setweight(to_tsvector('english',
  # coalesce("letters"."title"::text, '')), 'A') ||
  # setweight(to_tsvector('english', coalesce("letters"."body"::text, '')),
  # 'B')) @@ (to_tsquery('english', ''' ' || 'tab' || ' '''))))) AS
  # pg_search_7ad8dbe5dbed0dcda5e2fa ON "letters"."id" =
  # pg_search_7ad8dbe5dbed0dcda5e2fa.pg_search_id ORDER BY
  # pg_search_7ad8dbe5dbed0dcda5e2fa.rank DESC, "letters"."id" ASC
  #
  # You'll probably be able to take the query to test against from
  # the sql logs rails runs when you `Letter.search_full_text`
  pg_search_scope :search_full_text,
                  :against => { 
                    :title => 'A',
                    :body  => 'B'
                  },
                  :using => { 
                    :tsearch => { :dictionary => 'english' }
                  }
                                  

  def rendered_body
    # Debating if this should be cached in the db or generated
    # generated allows me to change the rendering...but how often will that
    # happen. For testing it'll stay here, but
    # I probably will end up
    # @TODO move rendering into `Letter#body=`
    doc = Kramdown::Document.new(body)
    rendered_body, warnings = LettersHelper::HTMLConverterWithoutLinks.convert(doc.root)
    return rendered_body
  end

  def update_spam_score
    dspam = Despamilator.new(body)
    self.spam_score = dspam.score
    self.spam_filters = []
    
    dspam.matches.each { |k| self.spam_filters <<  k[:filter].class.to_s + " @ " + k[:score].to_s }

    self.public =  dspam.score < 1
  end


  def self.find_by_zip(zip)
    conn = ActiveRecord::Base.connection.raw_connection
    query = <<EOS
select * from (
  select letters.*
  from letters
  left join (select letter_id 
    from letters_senate
    inner join zip2cds
      on zip2cds.state = letters_senate.state
    where zcta5 @> ARRAY[$1]
  ) letters_senate_zip
    on letters.id = letter_id
  left join (select letter_id 
    from letters_hofr
    inner join zip2cds
      on zip2cds.cd = letters_hofr.cd
    where zcta5 @> ARRAY[$1]
  ) letters_hofr_zip
    on letters.id = letters_hofr_zip.letter_id
  where public
  union all
  select letters.*
  from letters
  left join letters_senate
    on letters.id = letters_senate.letter_id
  left join  letters_hofr
    on letters.id = letters_hofr.letter_id
  where letters_senate.letter_id is null 
    and letters_hofr.letter_id is null
    and public
) letters_for_zip_or_none
group by 
  id, 
  title, 
  body, 
  created_at, 
  updated_at, 
  rendered_body, 
  spam_score, 
  spam_filters, 
  public
EOS
    q = conn.query(query, [zip])
    q.map { |c| Letter.new(c) }
  end
end

app/controllers/letters_controller.rb
require "kramdown"

class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :duplicate, :format]
  layout "plain", :only => :format

  # GET /letters
  # GET /letters.json
  def index
    @search_term = params['q']
    @zip = params['zip']
    if @search_term then
      @letters = Letter.search_full_text(@search_term)
    elsif @zip then
      @letters = Letter.find_by_zip(@zip)
    else
      @letters = Letter.all
    end
  end


  # GET /letters/1
  # GET /letters/1.json
  def show

    @sender = {
      :name => "Sender's Name",
      :street_address => "Street",
      :city => "City",
      :state => "State",
      :zip => "00000"
    }

    @recipient = {
      :name => "Sender's Name",
      :street_address => "Street",
      :city => "City",
      :state => "State",
      :zip => "00000"
    }

    @can_edit = can_edit
  end

  def select_legislators
    @critters = CongressCritter.find_by_zip(params[:zip])
    @sender = {
      :name => params[:name],
      :street_address => params[:street_address],
      :city => params[:city],
      :state => params[:state],
      :zip => params[:zip]
    }
  end

  def format
    @critters = params[:critters].map { |x| CongressCritter.find(x) }
    @sender = {
      :name => params[:name],
      :street_address => params[:street_address],
      :city => params[:city],
      :state => params[:state],
      :zip => params[:zip]
    }
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
    redirect_to @letter unless can_edit
  end

  # POST /letters/1/duplicate
  def duplicate
    @new_letter = @letter.dup
    @new_letter.categories = @letter.categories
    @letter = @new_letter

    if @letter.save
      add_letter_to_session
      redirect_to edit_letter_path(@letter)
    else
      format.html { render :new }
      format.json { render json: @letter.errors, status: :unprocessable_entity }
    end
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)
    unless params[:categories].nil? then
      for category in params[:categories]
        @letter.categories << category
      end
    end

    respond_to do |format|
      if @letter.save
        add_letter_to_session
        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    redirect_to @letter unless can_edit

    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  #def destroy
  #  @letter.destroy
  #  respond_to do |format|
  #    format.html { redirect_to letters_url, notice: 'Letter was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    def can_edit
      if can_edit_id @letter.id then
        return true unless edit_too_old @letter
        # if we can't edit, we might as well clear it from the session
        session[:letters].delete_if {|l| l == @letter.id }
      end
      return false
    end

    def can_edit_id(id)
      id = id.to_i
      unless session[:letters].nil? then
        return session[:letters].include? id
      end
      return false
    end

    def edit_too_old(letter)
      return letter.created_at + 1.hour < DateTime.now.utc
    end

    def add_letter_to_session
      session[:letters] = [] if session[:letters].nil?
      session[:letters] << @letter.id

      clean_session if session[:letters].length > 100
    end

    def clean_session
      session[:letters].delete_if do |l|
          l = Letter.find(l)
          return edit_too_old l
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.eager_load(:categories)
      if can_edit_id params[:id] then
        @letter = @letter.unscoped
      end
      @letter = @letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      p = params.require(:letter).permit(:title, :body, :categories=>[])
      if p[:categories] then
        for i in 0...p[:categories].length
          p[:categories][i] = Category.find(p[:categories][i])
        end
      end
      p
    end
end

app/helpers/letters_helper.rb
module LettersHelper
  class HTMLConverterWithoutLinks < Kramdown::Converter::Html 
    def convert_a(el, indent)
      inner(el, indent)
    end
  end
end

app/views/letters/_form.html.erb
<script>
$(function() {
  $('#categories').selectize({
      maxItems: null,
      mode: 'multi',
      valueField: 'id',
      labelField: 'display_name',
      searchField: ['name', 'aliases'],
      create: false,
      load: function(query, callback) {
          if (!query.length) return callback();
          $.ajax({
              url: '<%= categories_url(format: :json)%>?q=' + encodeURIComponent(query),
              type: 'GET',
              error: function() {
                  callback();
              },
              success: function(res) {
                  callback(res.slice(0, 10));
              }
          });
      }
  });

  $('#districts').selectize({
      maxItems: null,
      mode: 'multi',
      valueField: 'id',
      labelField: 'name',
      searchField: ['name', 'one_zip'],
      optgroupLabelField: 'type',
      optgroupField: 'type',
      create: false,
      load: function(query, callback) {
          var self = this;
          if (!query.length) return callback();
          $.ajax({
              url: '<%= districts_url(format: :json)%>?zip=' + encodeURIComponent(query),
              type: 'GET',
              error: function() {
                  callback();
              },
              success: function(res) {
                  $.each(res, function(index, value) {
                    self.addOptionGroup(value['type'], value);
                  });
                  self.refreshOptions();
                  callback(res.slice(0, 10));
              }
          });
      }
  });
});

</script>


<%= form_for(letter) do |f| %>
  <% if letter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(letter.errors.count, "error") %> prohibited this letter from being saved:</h2>

      <ul>
      <% letter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <label for="categories">Topics:
  <select multiple id="categories" name="letter[categories][]">
  <% for category in @letter.categories %>
    <option value="<%= category.id %>" selected><%=category.display_name%></option>
  <% end %>
  </select>
  </label>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <label for="districts"> Applicable Districts (leave blank for general letters)(enter your zip to show relevant districts)
  <select multiple id="districts" name="letter[districts][]">
  </select>
  </label>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/letters/_formatted.html.erb
<div id="formatted-letter">
  <div class="recipient-address">
    <p class="h-card">
      <span class="p-name"><%= recipient[:name] %></span>
      <span class="p-street-address"><%= recipient[:street_address]%></span>
      <span class="p-locality"><%= recipient[:city] %></span>
      <span class="p-region"><%=recipient[:state] %></span>
      <span class="p-postal-code"><%= recipient[:zip] %></span>
    </p>
  </div>
  <div class="sender-address">
    <p class="h-card">
      <span class="p-name"><%= sender[:name] %></span>
      <span class="p-street-address"><%= sender[:street_address]%></span>
      <span class="p-locality"><%= sender[:city] %></span>
      <span class="p-region"><%=sender[:state] %></span>
      <span class="p-postal-code"><%= sender[:zip] %></span>
    </p>
  </div>

  <p class="regarding">
    Re: <%= letter.title %>
  </p>

  <p>
    <div class="letter-body">
      <% if not letter.rendered_body.nil? then %>
      <%= letter.rendered_body.html_safe %>
      <% end %>
    </div>
  </p>

  <p>
  <p>Sincerely,</p>
  <p><%= sender[:name] %></p>

  </p>
</div>

app/views/letters/edit.html.erb
<h1>Editing Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

app/views/letters/format.html.erb
<% @critters.each_with_index do |critter, index| %>
<div style="<%="page-break-before: always" unless index == 0%>">
  <%= render 'formatted', letter: @letter, sender: @sender, recipient: critter.recipient_array %>
</div>
<% end %>

app/views/letters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Letters</h1>

<form method="GET" action="<%= letters_path %>">
  <label for="search-term">Search: </label>
  <input type="text" id="search-term" name="q" value="<%= @search_term %>">
  <input type="submit" value="Search">
</form>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @letters.each do |letter| %>
      <tr>
        <td><%= letter.title %></td>
        <td><%= link_to 'Show', letter_path(letter) %></td>
        <td><%= link_to 'Edit', edit_letter_path(letter) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Letter', new_letter_path %>

app/views/letters/new.html.erb
<h1>New Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Back', letters_path %>

app/views/letters/select_legislators.html.erb
  <form method="POST" action="<%= format_letter_path %>">
    <p>Select the legilators you'd like to address this letter to.</p>
    <% for critter in @critters %>
    <label for="critter-<%=critter.govtrack_id%>">
    <input type="checkbox" value="<%=critter.govtrack_id%>" name="critters[]" id="critter-<%=critter.govtrack_id%>">
    <%=critter.name%> (<%=critter.parentetical%>)
    </label>
    <% end %>
    <input type="hidden" id="name" name="name" value="<%=@sender[:name]%>">
    <input type="hidden" id="street" name="street_address" value="<%=@sender[:street_address]%>">
    <input type="hidden" id="city" name="city" value="<%=@sender[:city]%>">
    <input type="hidden" id="state" name="state" value="<%=@sender[:state]%>">
    <input type="hidden" id="zip" name="zip" value="<%=@sender[:zip]%>">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="submit" value="Address Letter">
  </form>

app/views/letters/show.html.erb
<p id="notice"><%= notice %></p>

<div id="categories">
  <ul>
  <% for category in @letter.categories %>
    <li class="category"><%= category.display_name %></span>
  <% end %>
  </ul>
</div>


<% if @can_edit then %>
<%= link_to 'Edit', edit_letter_path(@letter) %> |
<% end  %>
<%= link_to 'All Letters', letters_path %>
<%= button_to 'Duplicate & Edit',  duplicate_letter_path(@letter) %>

<p>
  <form method="POST" action="<%= select_legislator_letter_path %>">
    <p>Find your Congresspeople and format the letter: </p>
    <label for="name">name</label>
    <input type="text" id="name" name="name">
    <label for="street">street</label>
    <input type="text" id="street" name="street_address">
    <label for="city">city</label>
    <input type="text" id="city" name="city">
    <label for="state">state</label>
    <input type="text" id="state" name="state">
    <label for="zip">zip</label>
    <input type="text" id="zip" name="zip">
    <input type="submit" value="Search">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </form>
</p>

<%= render 'formatted', letter: @letter, sender: @sender, recipient: @recipient %>